### ISSUE TITLE
Console error when trying to run deobfuscator

### ISSUE THREAD

**Issue by phenomist** [ben-sb/obfuscator-io-deobfuscator#1]
Getting the following console error when I try to click on the button to deobfuscate, and there is no output:

Uncaught SyntaxError: 'import' and 'export' may appear only with 'sourceType: "module"' (1:726) (at parser.js:60:32)
    at instantiate (parser.js:60:32)
    at constructor (parser.js:355:12)
    at Parser.raise (parser.js:3232:19)
    at Parser.assertModuleNodeAllowed (parser.js:12805:12)
    at Parser.parseStatementContent (parser.js:12780:14)
    at Parser.parseStatementLike (parser.js:12650:17)
    at Parser.parseModuleItem (parser.js:12627:17)
    at Parser.parseBlockOrModuleBlockBody (parser.js:13254:36)
    at Parser.parseBlockBody (parser.js:13247:10)
    at Parser.parseProgram (parser.js:12526:10)

**Comment by ben-sb** [comment]
Should be fixed by https://github.com/ben-sb/obfuscator-io-deobfuscator/pull/2
