### ISSUE TITLE
SyntaxError when running on the website

### ISSUE THREAD

**Issue by mbomb007** [ben-sb/obfuscator-io-deobfuscator#10]
On both Firefox and Chrome-like, I get this error in my browser console when clicking "Deobfuscate".

```
Uncaught SyntaxError: This experimental syntax requires enabling one of the following parser plugin(s): "jsx", "flow", "typescript". (1:0)
    at constructor (parser.js:372:21)
    at Parser.raise (parser.js:3267:21)
    at Parser.expectOnePlugin (parser.js:3316:20)
    at Parser.parseExprAtom (parser.js:11346:18)
    at Parser.parseExprSubscripts (parser.js:10999:25)
    at Parser.parseUpdate (parser.js:10981:23)
    at Parser.parseMaybeUnary (parser.js:10957:25)
    at Parser.parseMaybeUnaryOrPrivate (parser.js:10794:63)
    at Parser.parseExprOps (parser.js:10799:25)
    at Parser.parseMaybeConditional (parser.js:10776:25)
```

**Comment by ben-sb** [comment]
Are you trying to deobfuscate TypeScript or JSX (e.g. React code)? If so it isn't supported via the website. You can try cloning the repo and enabling the Babel parser plugins that the error message mentions, but the deobfuscator isn't intended to support them so can't guarantee it will work.

**Comment by ben-sb** [comment]
It doesn't support deobfuscating HTML, no. You can paste the content of any JS script tags into the deobfuscator though and it should work.

I will add better error handling to my to-do list.

**Comment by ben-sb** [comment]
You could use a HTML parser and select the content of any JS script tags. If you wanted it to work for non-inline JS then you would have to also fetch the source before deobfuscating.
