### ISSUE TITLE
SyntaxError: Unexpected token ?

### ISSUE THREAD

**Issue by Rakuen409** [ben-sb/obfuscator-io-deobfuscator#42]
enableOrNameAndArgs = enableOrNameAndArgs ?? 'help [command]';
                                               ^

SyntaxError: Unexpected token ?
    at Module._compile (internal/modules/cjs/loader.js:718:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)

**Comment by ben-sb** [comment]
Could be you are using an older NodeJS version, can you try v20+

**Comment by Rakuen409** [comment]
sorry, It's my mistake.
