### ISSUE TITLE
Uncaught SyntaxError: TypeError

### ISSUE THREAD

**Issue by mathactivities** [ben-sb/obfuscator-io-deobfuscator#43]
While I was de-obfuscating my code on <a href = "https://obf-io.deobfuscate.io/">obf-io.deobfuscate.io</a> My javascript code wouldn't de-obfuscate. Here is the error:
Uncaught SyntaxError: Unexpected token, expected "," (1:138845) (at deobfuscator.js:1:197711)
    at c (deobfuscator.js:1:197711)
    at e (deobfuscator.js:1:213903)
    at on.raise (deobfuscator.js:1:261330)
    at on.unexpected (deobfuscator.js:1:261762)
    at on.expect (deobfuscator.js:1:266297)
    at on.parseExprList (deobfuscator.js:1:439156)
    at on.parseArrayLike (deobfuscator.js:1:437299)
    at on.parseExprAtom (deobfuscator.js:1:423372)
    at on.parseExprSubscripts (deobfuscator.js:1:417892)
    at on.parseUpdate (deobfuscator.js:1:417515)

**Comment by ben-sb** [comment]
Can you provide the code you were trying to deobfuscate?

**Comment by mathactivities** [comment]
Now it works. Thanks.
